### ISSUE TITLE
ONNX dynamic input shape export support?

### ISSUE THREAD

**Issue by gtejani** [Clika/clika_compression_examples#2]
Is dynamic input shape for ONNX export not allowed in deployment setting?
It seems to take the shape defined during quantization-aware training as default.

**Comment by jl749** [comment]
Hi @gtejani 

Sorry for getting back to you late. We are currently using email channels only for beta supports.
Please email us at [jlee@clika.io]() next time.


<ins>**0.1.2**</ins> beta version is currently not generating a dynamically shaped onnx graph due to a bug.
<ins>**0.1.3**</ins> update scheduled for tomorrow evening (September 11th, KST) should be able to fix it.

I will leave a comment once the new whl package is uploaded on pypi.

Thank you for reporting a problem.

**Comment by jl749** [comment]
Hi @gtejani

The new version (0.1.3) is available now!
In order to update your local environment, please follow the installation guide on the docs [page](https://docs.clika.io/docs/installation/index.html#clika-compression-installation).
```
pip install --force "clika-compression" --extra-index-url \
https://license:$CC_LICENSE_KEY@license.clika.io/simple
```

To generate dynamically shaped ONNX graph, specify `input_shapes` parameter inside `deploy` function.
e.g.
```
    engine.deploy(
        ...
        input_shapes=[1, 3, None, None],
    )
```
ONNX file generated:
![image](https://github.com/Clika/clika_compression_examples/assets/67103130/501c893c-000b-4bd8-88d9-90e42c3587fd)

Thank you
